"""ORM models for the CRM backend."""

from crm_backend.models.crm_role import CrmRole
from crm_backend.models.crm_user import CrmUser
from crm_backend.models.crm_user_role import CrmUserRole
from crm_backend.models.permission import RolePermission, UserPermission
from crm_backend.models.activity_log import ActivityLog, ActivityLogArchive
from crm_backend.models.stock_category import StockCategory
from crm_backend.models.stock_level import StockLevel
from crm_backend.models.stock_movement import StockMovement, StockMovementType
from crm_backend.models.stock_product import StockProduct
from crm_backend.models.material_flow import (
	InventoryDispatch,
	InventoryDispatchItem,
	InventoryRequest,
	InventoryRequestItem,
	InventoryRequestStatus,
	InventorySourceType,
	TaskExtraMaterial,
	TaskRequiredMaterial,
	TicketRequiredMaterial,
	TemplateMaterial,
)
from crm_backend.models.task_reference import Client, ClientLocation, Location
from crm_backend.models.task_execution import (
	Subtask,
	SubtaskAssignment,
	TaskPreFormAttachment,
	TaskPreFormFieldType,
	TaskPreFormFieldValue,
	TaskPreFormInstance,
	TaskPreFormResponse,
	TaskSatisfactionForm,
	TaskSatisfactionResponse,
	TaskAttachment,
	TaskAttachmentType,
	TaskTemplatePreForm,
	TaskTemplatePreFormField,
	SubtaskChecklistProgress,
	SubtaskItemValue,
	SubtaskStatus,
	SubtaskTransition,
	Task,
	TaskAuditEvent,
	TaskComment,
	TaskCommentMention,
	TaskCommentType,
	TaskStatus,
	TransitionAction,
)
from crm_backend.models.ticket import (
	Ticket,
	TicketAssignmentHistory,
	TicketAttachment,
	TicketAttachmentType,
	TicketAuditEvent,
	TicketComment,
	TicketCommentMention,
	TicketCommentType,
	TicketPriority,
	TicketSatisfactionForm,
	TicketSatisfactionMedia,
	TicketSatisfactionResponse,
	TicketStatus,
	TicketStatusTransition,
	TicketTransitionAction,
)
from crm_backend.models.task_template import NextAssignmentPolicy, SubtaskType, TaskTemplate, TaskTemplateItem, TaskTemplateSubtask, TemplateItemType
from crm_backend.models.warehouse import Warehouse
from crm_backend.models.notification import Notification, NotificationEntityType, NotificationType
from crm_backend.models.push_subscription import PushSubscription
from crm_backend.models.settings import CrmCategory, CrmPriority, CrmStatus, NotificationRule, SlaRule

__all__ = [
	"CrmRole",
	"CrmUser",
	"CrmUserRole",
	"RolePermission",
	"UserPermission",
	"ActivityLog",
	"ActivityLogArchive",
	"StockCategory",
	"StockLevel",
	"StockMovement",
	"StockMovementType",
	"StockProduct",
	"InventoryDispatch",
	"InventoryDispatchItem",
	"InventoryRequest",
	"InventoryRequestItem",
	"InventoryRequestStatus",
	"InventorySourceType",
	"TaskExtraMaterial",
	"TaskRequiredMaterial",
	"TicketRequiredMaterial",
	"TemplateMaterial",
	"Client",
	"ClientLocation",
	"Location",
	"Subtask",
	"SubtaskAssignment",
	"TaskPreFormAttachment",
	"TaskPreFormFieldType",
	"TaskPreFormFieldValue",
	"TaskPreFormInstance",
	"TaskPreFormResponse",
	"TaskSatisfactionForm",
	"TaskSatisfactionResponse",
	"TaskAttachment",
	"TaskAttachmentType",
	"TaskTemplatePreForm",
	"TaskTemplatePreFormField",
	"SubtaskChecklistProgress",
	"SubtaskItemValue",
	"SubtaskStatus",
	"SubtaskTransition",
	"Task",
	"TaskAuditEvent",
	"TaskComment",
	"TaskCommentMention",
	"TaskCommentType",
	"TaskStatus",
	"TaskTemplate",
	"TaskTemplateItem",
	"TaskTemplateSubtask",
	"TemplateItemType",
	"NextAssignmentPolicy",
	"SubtaskType",
	"TransitionAction",
	"Ticket",
	"TicketAssignmentHistory",
	"TicketAttachment",
	"TicketAttachmentType",
	"TicketAuditEvent",
	"TicketComment",
	"TicketCommentMention",
	"TicketCommentType",
	"TicketPriority",
	"TicketSatisfactionForm",
	"TicketSatisfactionMedia",
	"TicketSatisfactionResponse",
	"TicketStatus",
	"TicketStatusTransition",
	"TicketTransitionAction",
	"Warehouse",
	"Notification",
	"NotificationEntityType",
	"NotificationType",
	"PushSubscription",
	"CrmCategory",
	"CrmPriority",
	"CrmStatus",
	"SlaRule",
	"NotificationRule",
]
