"""Ticket module API tests."""

from __future__ import annotations

from io import BytesIO

from sqlalchemy import select

from crm_backend.adapters.auth_service_adapter import ActiveMembershipContext, AuthenticatedAuthResult
from crm_backend.api.dependencies import get_auth_service_adapter
from crm_backend.models import Client, CrmRole, CrmUser, CrmUserRole, Location, StockProduct, TicketAttachment


class FakeTicketAuthAdapter:
    """Fake auth adapter returning deterministic CRM sessions per bearer token."""

    USER_FIXTURES = {
        "admin-token": {
            "auth_user_id": "auth-admin",
            "email": "admin.crm@microtv.com",
            "display_name": "Admin CRM",
            "roles": ["platform_admin"],
            "tenant_id": "MICROTV",
        },
        "ejecutivo-token": {
            "auth_user_id": "auth-ejecutivo",
            "email": "ejecutivo.crm@yccbrothers.com",
            "display_name": "Ejecutivo CRM",
            "roles": ["ejecutivo"],
            "tenant_id": "YCC",
        },
        "tech-token": {
            "auth_user_id": "auth-tech",
            "email": "tecnico.crm@yccbrothers.com",
            "display_name": "Tecnico Campo",
            "roles": [],
            "tenant_id": "YCC",
        },
        "tech-2-token": {
            "auth_user_id": "auth-tech-2",
            "email": "tecnico2.crm@yccbrothers.com",
            "display_name": "Tecnico Campo 2",
            "roles": [],
            "tenant_id": "YCC",
        },
        "deposito-token": {
            "auth_user_id": "auth-deposito",
            "email": "deposito.crm@yccbrothers.com",
            "display_name": "Encargado Deposito",
            "roles": [],
            "tenant_id": "YCC",
        },
    }

    def validate_access_token(self, access_token: str) -> AuthenticatedAuthResult:
        fixture = self.USER_FIXTURES[access_token]
        return AuthenticatedAuthResult(
            access_token=access_token,
            refresh_token="refresh-token",
            token_type="bearer",
            expires_in=3600,
            refresh_expires_in=86400,
            auth_user_id=fixture["auth_user_id"],
            email=fixture["email"],
            display_name=fixture["display_name"],
            active_membership=ActiveMembershipContext(
                membership_id=f"membership-{fixture['auth_user_id']}",
                tenant_type="company",
                tenant_id=fixture["tenant_id"],
                roles=fixture["roles"],
            ),
            claims={"sub": fixture["auth_user_id"], "email": fixture["email"]},
        )

    def login(self, *, email: str, password: str):
        raise NotImplementedError


def _auth_header(token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {token}"}


def _seed_local_role_user(db_session, *, role_key: str, auth_user_id: str, email: str, display_name: str) -> CrmUser:
    role = db_session.scalar(select(CrmRole).where(CrmRole.role_key == role_key))
    if role is None:
        raise AssertionError(f"No se encontró el rol {role_key} seed.")

    crm_user = CrmUser(auth_user_id=auth_user_id, email=email, display_name=display_name)
    crm_user.assigned_roles.append(CrmUserRole(crm_role_id=role.crm_role_id, role=role))
    db_session.add(crm_user)
    db_session.commit()
    db_session.refresh(crm_user)
    return crm_user


def _seed_client_with_location(db_session) -> tuple[Client, Location]:
    client = Client(business_name="Cliente Ticket SA", tax_id="30-87654321-9", email="tickets@cliente.test")
    location = Location(latitude=-34.603722, longitude=-58.381592, address_label="Oficina central", formatted_address="Oficina central")
    db_session.add(client)
    db_session.add(location)
    db_session.commit()
    db_session.refresh(client)
    db_session.refresh(location)
    return client, location


def test_admin_can_create_ticket_with_autogenerated_number(client, db_session) -> None:
    tech_user = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    create_response = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Pantalla sin señal",
            "description": "El monitor principal no muestra contenido.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "HIGH",
            "assigned_role_id": tech_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user.crm_user_id,
        },
    )

    assert create_response.status_code == 200, create_response.text
    body = create_response.json()
    assert body["ticket_number"].startswith("TCK-")
    assert body["status"] == "IN_PROGRESS"
    assert body["assigned_user_id"] == tech_user.crm_user_id
    assert body["assigned_role_id"] == tech_user.assigned_roles[0].crm_role_id

    assigned_response = client.get("/tickets/assigned/me", headers=_auth_header("tech-token"))
    assert assigned_response.status_code == 200, assigned_response.text
    assert any(item["ticket_id"] == body["ticket_id"] for item in assigned_response.json())


def test_operational_roles_can_create_locations_for_ticket_flows(client, db_session) -> None:
    _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    location_response = client.post(
        "/locations",
        headers=_auth_header("tech-token"),
        json={
            "latitude": -34.6037,
            "longitude": -58.3816,
            "address_label": "Ubicacion visita tecnica",
            "formatted_address": "Av. 9 de Julio, CABA",
        },
    )

    assert location_response.status_code == 201, location_response.text
    body = location_response.json()
    assert body["location_id"]
    assert body["address_label"] == "Ubicacion visita tecnica"


def test_closing_ticket_requires_comment_and_moves_to_history(client, db_session) -> None:
    tech_user = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    created = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Revisión de gabinete",
            "description": "Se detectó sobretemperatura.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "MEDIUM",
            "assigned_role_id": tech_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user.crm_user_id,
        },
    )
    assert created.status_code == 200, created.text
    ticket_id = created.json()["ticket_id"]

    invalid_close = client.patch(
        f"/tickets/{ticket_id}/close",
        headers=_auth_header("tech-token"),
        json={"comment": "", "attachment_ids": []},
    )
    assert invalid_close.status_code == 422
    assert invalid_close.json()["error"]["code"] == "ticket_validation_error"

    close_response = client.patch(
        f"/tickets/{ticket_id}/close",
        headers=_auth_header("tech-token"),
        json={"comment": "Cierre técnico con diagnóstico final", "attachment_ids": []},
    )
    assert close_response.status_code == 200, close_response.text
    closed_body = close_response.json()
    assert closed_body["status"] == "CLOSED"
    assert closed_body["closed_by_crm_user_id"] == tech_user.crm_user_id

    history_response = client.get("/tickets/history/me", headers=_auth_header("admin-token"))
    assert history_response.status_code == 200, history_response.text
    assert any(item["ticket_id"] == ticket_id for item in history_response.json())


def test_tecnico_can_reassign_to_deposito_and_same_role(client, db_session) -> None:
    tech_user = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    tech_user_2 = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech-2",
        email="tecnico2.crm@yccbrothers.com",
        display_name="Tecnico Campo 2",
    )
    deposito_user = _seed_local_role_user(
        db_session,
        role_key="encargado_deposito",
        auth_user_id="auth-deposito",
        email="deposito.crm@yccbrothers.com",
        display_name="Encargado Deposito",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    created = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Cambio de placa",
            "description": "Requiere reasignación interna de técnico.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "HIGH",
            "assigned_role_id": tech_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user.crm_user_id,
        },
    )
    assert created.status_code == 200, created.text
    ticket_id = created.json()["ticket_id"]

    allowed_cross_role = client.patch(
        f"/tickets/{ticket_id}/assignment",
        headers=_auth_header("tech-token"),
        json={
            "assigned_role_id": deposito_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": deposito_user.crm_user_id,
            "notes": "Derivar a depósito",
        },
    )
    assert allowed_cross_role.status_code == 200, allowed_cross_role.text
    assert allowed_cross_role.json()["assigned_user_id"] == deposito_user.crm_user_id

    allowed_same_role = client.patch(
        f"/tickets/{ticket_id}/assignment",
        headers=_auth_header("tech-token"),
        json={
            "assigned_role_id": tech_user_2.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user_2.crm_user_id,
            "notes": "Cambio de guardia técnica",
        },
    )
    assert allowed_same_role.status_code == 200, allowed_same_role.text
    body = allowed_same_role.json()
    assert body["assigned_user_id"] == tech_user_2.crm_user_id


def test_tecnico_can_escalate_ticket_to_admin_role(client, db_session) -> None:
    tech_user = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    admin_user = _seed_local_role_user(
        db_session,
        role_key="admin_crm",
        auth_user_id="auth-admin",
        email="admin.crm@microtv.com",
        display_name="Admin CRM",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    created = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Escalamiento tecnico",
            "description": "Incidencia requiere escalamiento a administrador.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "HIGH",
            "assigned_role_id": tech_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user.crm_user_id,
        },
    )
    assert created.status_code == 200, created.text
    ticket_id = created.json()["ticket_id"]

    escalated = client.patch(
        f"/tickets/{ticket_id}/assignment",
        headers=_auth_header("tech-token"),
        json={
            "assigned_role_id": admin_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": None,
            "notes": "Escalamiento tecnico a administrador",
        },
    )
    assert escalated.status_code == 200, escalated.text
    body = escalated.json()
    assert body["assigned_role_id"] == admin_user.assigned_roles[0].crm_role_id
    assert body["assigned_role_key"] == "admin"


def test_deposito_can_escalate_ticket_to_admin_role(client, db_session) -> None:
    deposito_user = _seed_local_role_user(
        db_session,
        role_key="encargado_deposito",
        auth_user_id="auth-deposito",
        email="deposito.crm@yccbrothers.com",
        display_name="Encargado Deposito",
    )
    admin_user = _seed_local_role_user(
        db_session,
        role_key="admin_crm",
        auth_user_id="auth-admin",
        email="admin.crm@microtv.com",
        display_name="Admin CRM",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    created = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Escalamiento deposito",
            "description": "Incidencia operativa para escalar a administrador.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "MEDIUM",
            "assigned_role_id": deposito_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": deposito_user.crm_user_id,
        },
    )
    assert created.status_code == 200, created.text
    ticket_id = created.json()["ticket_id"]

    escalated = client.patch(
        f"/tickets/{ticket_id}/assignment",
        headers=_auth_header("deposito-token"),
        json={
            "assigned_role_id": admin_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": None,
            "notes": "Escalamiento operativo a administrador",
        },
    )
    assert escalated.status_code == 200, escalated.text
    body = escalated.json()
    assert body["assigned_role_id"] == admin_user.assigned_roles[0].crm_role_id
    assert body["assigned_role_key"] == "admin"


def test_role_catalog_includes_admin_for_tecnico_and_deposito(client, db_session) -> None:
    _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    _seed_local_role_user(
        db_session,
        role_key="encargado_deposito",
        auth_user_id="auth-deposito",
        email="deposito.crm@yccbrothers.com",
        display_name="Encargado Deposito",
    )
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    tech_roles_response = client.get("/tickets/roles", headers=_auth_header("tech-token"))
    assert tech_roles_response.status_code == 200, tech_roles_response.text
    tech_role_keys = {item["role_key"] for item in tech_roles_response.json()}
    assert "admin_crm" in tech_role_keys

    deposito_roles_response = client.get("/tickets/roles", headers=_auth_header("deposito-token"))
    assert deposito_roles_response.status_code == 200, deposito_roles_response.text
    deposito_role_keys = {item["role_key"] for item in deposito_roles_response.json()}
    assert "admin_crm" in deposito_role_keys


def test_ticket_comment_can_link_uploaded_attachment(client, db_session) -> None:
    tech_user = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    created = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Falla intermitente",
            "description": "Se registra con evidencia multimedia.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "LOW",
            "assigned_role_id": tech_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user.crm_user_id,
        },
    )
    assert created.status_code == 200, created.text
    ticket_id = created.json()["ticket_id"]

    upload_response = client.post(
        f"/tickets/{ticket_id}/attachments",
        headers=_auth_header("tech-token"),
        files={"files": ("evidencia.jpg", BytesIO(b"fake-image-content"), "image/jpeg")},
    )
    assert upload_response.status_code == 200, upload_response.text
    uploaded = upload_response.json()
    assert len(uploaded) == 1

    comment_response = client.post(
        f"/tickets/{ticket_id}/comments",
        headers=_auth_header("tech-token"),
        json={"body": "Adjunto evidencia visual", "attachment_ids": [uploaded[0]["id"]]},
    )
    assert comment_response.status_code == 200, comment_response.text
    body = comment_response.json()
    persisted_comment = next(comment for comment in body["comments"] if comment["body"] == "Adjunto evidencia visual")
    assert len(persisted_comment["attachments"]) == 1
    assert persisted_comment["attachments"][0]["id"] == uploaded[0]["id"]

    persisted_attachment = db_session.scalar(select(TicketAttachment).where(TicketAttachment.attachment_id == uploaded[0]["id"]))
    assert persisted_attachment is not None
    assert persisted_attachment.ticket_comment_id == persisted_comment["ticket_comment_id"]


def test_ticket_inventory_request_blocks_technician_until_dispatch_returns_ticket(client, db_session) -> None:
    tech_user = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    _seed_local_role_user(
        db_session,
        role_key="encargado_deposito",
        auth_user_id="auth-deposito",
        email="deposito.crm@yccbrothers.com",
        display_name="Encargado Deposito",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    created = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Ticket con solicitud a deposito",
            "description": "El tecnico requiere materiales antes de continuar.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "HIGH",
            "assigned_role_id": tech_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user.crm_user_id,
        },
    )
    assert created.status_code == 200, created.text
    ticket_id = created.json()["ticket_id"]

    dispatchable_product = db_session.scalar(
        select(StockProduct).where(StockProduct.is_active.is_(True), StockProduct.requires_tracking.is_(False))
    )
    assert dispatchable_product is not None

    request_response = client.post(
        "/inventory-flow/requests",
        headers=_auth_header("tech-token"),
        json={
            "source_type": "TICKET",
            "external_ticket_id": ticket_id,
            "request_reason": "Falta equipamiento para continuar",
            "items": [{"product_id": dispatchable_product.product_id, "quantity_requested": 3, "notes": "Urgente"}],
        },
    )
    assert request_response.status_code == 200, request_response.text
    request_body = request_response.json()
    assert request_body["request_status"] == "PENDING"
    request_id = request_body["inventory_request_id"]

    detail_in_deposito = client.get(f"/tickets/{ticket_id}", headers=_auth_header("tech-token"))
    assert detail_in_deposito.status_code == 200, detail_in_deposito.text
    detail_body = detail_in_deposito.json()
    assert detail_body["assigned_user_id"] is None
    assert detail_body["assigned_role_label"] == "Encargado de Deposito"

    blocked_comment = client.post(
        f"/tickets/{ticket_id}/comments",
        headers=_auth_header("tech-token"),
        json={"body": "Intento operar mientras esta en deposito", "attachment_ids": []},
    )
    assert blocked_comment.status_code == 403

    review_response = client.post(
        f"/inventory-flow/requests/{request_id}/review",
        headers=_auth_header("deposito-token"),
        json={"status": "APPROVED", "review_notes": "Autorizado para despacho"},
    )
    assert review_response.status_code == 200, review_response.text
    assert review_response.json()["request_status"] == "PENDING_DISPATCH"

    dispatch_response = client.post(
        f"/inventory-flow/requests/{request_id}/dispatches",
        headers=_auth_header("deposito-token"),
        json={
            "request_id": request_id,
            "dispatch_notes": "Despacho confirmado para ticket",
            "items": [{"product_id": dispatchable_product.product_id, "quantity_dispatched": 3}],
        },
    )
    assert dispatch_response.status_code == 200, dispatch_response.text
    dispatch_body = dispatch_response.json()
    assert dispatch_body["items"][0]["quantity_dispatched"] == 3
    dispatch_item_id = dispatch_body["items"][0]["inventory_dispatch_item_id"]

    detail_returned = client.get(f"/tickets/{ticket_id}", headers=_auth_header("tech-token"))
    assert detail_returned.status_code == 200, detail_returned.text
    returned_body = detail_returned.json()
    assert returned_body["assigned_user_id"] == tech_user.crm_user_id

    source_flow_response = client.get(f"/inventory-flow/sources/TICKET/{ticket_id}", headers=_auth_header("tech-token"))
    assert source_flow_response.status_code == 200, source_flow_response.text
    source_flow_body = source_flow_response.json()
    linked_request = next(item for item in source_flow_body["requests"] if item["inventory_request_id"] == request_id)
    assert linked_request["request_status"] == "PENDING_RECEIPT"

    blocked_status_change = client.patch(
        f"/tickets/{ticket_id}/status",
        headers=_auth_header("tech-token"),
        json={"to_status": "ON_HOLD", "comment": "Intento de cambio antes de recibir", "attachment_ids": []},
    )
    assert blocked_status_change.status_code == 409, blocked_status_change.text

    blocked_close = client.patch(
        f"/tickets/{ticket_id}/close",
        headers=_auth_header("tech-token"),
        json={"comment": "Intento de cierre antes de recibir", "attachment_ids": []},
    )
    assert blocked_close.status_code == 409, blocked_close.text

    resumed_comment = client.post(
        f"/tickets/{ticket_id}/comments",
        headers=_auth_header("tech-token"),
        json={"body": "Ticket retomado luego del despacho", "attachment_ids": []},
    )
    assert resumed_comment.status_code == 200, resumed_comment.text

    reception_confirmation = client.post(
        f"/inventory-flow/dispatch-items/{dispatch_item_id}/confirmations",
        headers=_auth_header("tech-token"),
        json={"confirmation_type": "received", "reception_comment": "Material recibido completo"},
    )
    assert reception_confirmation.status_code == 200, reception_confirmation.text

    source_flow_after_receipt = client.get(f"/inventory-flow/sources/TICKET/{ticket_id}", headers=_auth_header("tech-token"))
    assert source_flow_after_receipt.status_code == 200, source_flow_after_receipt.text
    source_flow_after_receipt_body = source_flow_after_receipt.json()
    linked_request_after_receipt = next(item for item in source_flow_after_receipt_body["requests"] if item["inventory_request_id"] == request_id)
    assert linked_request_after_receipt["request_status"] == "COMPLETED"


def test_ticket_inventory_request_rejection_requires_comment_and_returns_ticket_to_requester(client, db_session) -> None:
    tech_user = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    _seed_local_role_user(
        db_session,
        role_key="encargado_deposito",
        auth_user_id="auth-deposito",
        email="deposito.crm@yccbrothers.com",
        display_name="Encargado Deposito",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    created = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Ticket con rechazo de depósito",
            "description": "La solicitud será rechazada y debe volver al técnico.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "HIGH",
            "assigned_role_id": tech_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user.crm_user_id,
        },
    )
    assert created.status_code == 200, created.text
    ticket_id = created.json()["ticket_id"]

    dispatchable_product = db_session.scalar(
        select(StockProduct).where(StockProduct.is_active.is_(True), StockProduct.requires_tracking.is_(False))
    )
    assert dispatchable_product is not None

    request_response = client.post(
        "/inventory-flow/requests",
        headers=_auth_header("tech-token"),
        json={
            "source_type": "TICKET",
            "external_ticket_id": ticket_id,
            "request_reason": "Necesita revisión de depósito",
            "items": [{"product_id": dispatchable_product.product_id, "quantity_requested": 1, "notes": "Urgente"}],
        },
    )
    assert request_response.status_code == 200, request_response.text
    request_id = request_response.json()["inventory_request_id"]

    missing_comment_reject = client.post(
        f"/inventory-flow/requests/{request_id}/review",
        headers=_auth_header("deposito-token"),
        json={"status": "REJECTED", "review_notes": ""},
    )
    assert missing_comment_reject.status_code == 422, missing_comment_reject.text

    reject_response = client.post(
        f"/inventory-flow/requests/{request_id}/review",
        headers=_auth_header("deposito-token"),
        json={"status": "REJECTED", "review_notes": "Sin stock disponible para el item solicitado"},
    )
    assert reject_response.status_code == 200, reject_response.text
    rejected_body = reject_response.json()
    assert rejected_body["request_status"] == "REJECTED"
    assert rejected_body["review_notes"] == "Sin stock disponible para el item solicitado"

    detail_after_reject = client.get(f"/tickets/{ticket_id}", headers=_auth_header("tech-token"))
    assert detail_after_reject.status_code == 200, detail_after_reject.text
    detail_body = detail_after_reject.json()
    assert detail_body["assigned_user_id"] == tech_user.crm_user_id

    resumed_comment = client.post(
        f"/tickets/{ticket_id}/comments",
        headers=_auth_header("tech-token"),
        json={"body": "Retomo operación luego del rechazo de depósito", "attachment_ids": []},
    )
    assert resumed_comment.status_code == 200, resumed_comment.text


def test_closed_ticket_reopen_requires_comment_and_authorized_actor(client, db_session) -> None:
    tech_user = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    _seed_local_role_user(
        db_session,
        role_key="ejecutivo",
        auth_user_id="auth-ejecutivo",
        email="ejecutivo.crm@yccbrothers.com",
        display_name="Ejecutivo CRM",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    created = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Ticket cerrado y reabierto",
            "description": "Debe poder volver a flujo operativo con motivo.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "MEDIUM",
            "assigned_role_id": tech_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user.crm_user_id,
        },
    )
    assert created.status_code == 200, created.text
    ticket_id = created.json()["ticket_id"]

    close_response = client.patch(
        f"/tickets/{ticket_id}/close",
        headers=_auth_header("admin-token"),
        json={"comment": "Cierre ejecutivo", "attachment_ids": []},
    )
    assert close_response.status_code == 200, close_response.text
    assert close_response.json()["status"] == "CLOSED"

    reopen_without_comment = client.patch(
        f"/tickets/{ticket_id}/reopen",
        headers=_auth_header("admin-token"),
        json={"comment": ""},
    )
    assert reopen_without_comment.status_code == 422, reopen_without_comment.text

    unauthorized_reopen = client.patch(
        f"/tickets/{ticket_id}/reopen",
        headers=_auth_header("tech-token"),
        json={"comment": "No debería poder reabrir"},
    )
    assert unauthorized_reopen.status_code == 403, unauthorized_reopen.text

    reopen_response = client.patch(
        f"/tickets/{ticket_id}/reopen",
        headers=_auth_header("ejecutivo-token"),
        json={"comment": "El cliente reporta que la falla persiste"},
    )
    assert reopen_response.status_code == 200, reopen_response.text
    reopened_body = reopen_response.json()
    assert reopened_body["status"] == "IN_PROGRESS"
    assert reopened_body["closed_by_crm_user_id"] is None
    assert reopened_body["closed_at"] is None
    assert reopened_body["assigned_user_id"] == tech_user.crm_user_id
    assert any(comment["body"] == "El cliente reporta que la falla persiste" for comment in reopened_body["comments"])


def test_pending_ticket_can_be_rejected_by_executive_with_mandatory_comment(client, db_session) -> None:
    tech_user = _seed_local_role_user(
        db_session,
        role_key="tecnico_campo",
        auth_user_id="auth-tech",
        email="tecnico.crm@yccbrothers.com",
        display_name="Tecnico Campo",
    )
    _seed_local_role_user(
        db_session,
        role_key="ejecutivo",
        auth_user_id="auth-ejecutivo",
        email="ejecutivo.crm@yccbrothers.com",
        display_name="Ejecutivo CRM",
    )
    client_entity, location = _seed_client_with_location(db_session)
    client.app.dependency_overrides[get_auth_service_adapter] = lambda: FakeTicketAuthAdapter()

    created = client.post(
        "/tickets",
        headers=_auth_header("admin-token"),
        json={
            "title": "Ticket pendiente de aprobación",
            "description": "El ejecutivo debe poder rechazar el cierre.",
            "client_id": client_entity.client_id,
            "location_id": location.location_id,
            "priority": "MEDIUM",
            "assigned_role_id": tech_user.assigned_roles[0].crm_role_id,
            "assigned_user_id": tech_user.crm_user_id,
        },
    )
    assert created.status_code == 200, created.text
    ticket_id = created.json()["ticket_id"]

    close_response = client.patch(
        f"/tickets/{ticket_id}/close",
        headers=_auth_header("tech-token"),
        json={"comment": "Trabajo terminado", "attachment_ids": []},
    )
    assert close_response.status_code == 200, close_response.text
    assert close_response.json()["status"] == "PENDING_APPROVAL"

    reject_without_comment = client.patch(
        f"/tickets/{ticket_id}/reject",
        headers=_auth_header("ejecutivo-token"),
        json={"comment": ""},
    )
    assert reject_without_comment.status_code == 422, reject_without_comment.text

    reject_response = client.patch(
        f"/tickets/{ticket_id}/reject",
        headers=_auth_header("ejecutivo-token"),
        json={"comment": "Falta evidencia fotográfica y validación final."},
    )
    assert reject_response.status_code == 200, reject_response.text
    rejected_body = reject_response.json()
    assert rejected_body["status"] == "IN_PROGRESS"
    assert rejected_body["assigned_user_id"] == tech_user.crm_user_id
    assert rejected_body["closed_by_crm_user_id"] is None
    assert rejected_body["resolved_by_crm_user_id"] is None
    assert any(comment["body"] == "Falta evidencia fotográfica y validación final." for comment in rejected_body["comments"])
