"""API schema exports."""

from crm_backend.schemas.auth import (
    AccessPendingResponse,
    ActiveMembershipResponse,
    AuthenticatedUserResponse,
    ContextSelectionRequiredResponse,
    LoginRequest,
    LoginSuccessResponse,
    MembershipOptionResponse,
    TokenBundleResponse,
)
from crm_backend.schemas.common import ErrorDetailResponse, ErrorResponse
from crm_backend.schemas.clients import (
    ClientLocationPayload,
    ClientLocationResponse,
    ClientSummaryResponse,
    CreateClientRequest,
    UpdateClientRequest,
)
from crm_backend.schemas.crm_users import CrmUserOptionResponse
from crm_backend.schemas.locations import CreateLocationRequest, LocationResponse
from crm_backend.schemas.material_flow import (
    ConfirmDispatchItemRequest,
    CreateInventoryRequestRequest,
    CreateTaskDispatchRequest,
    InventoryDispatchItemResponse,
    InventoryDispatchResponse,
    InventoryRequestItemResponse,
    InventoryRequestResponse,
    InventorySourceFlowResponse,
    RequiredMaterialResponse,
    RequiredMaterialWriteRequest,
    ReviewInventoryRequestRequest,
)
from crm_backend.schemas.stock import (
    CreateStockProductRequest,
    StockAdjustmentRequest,
    StockCategoryResponse,
    StockProductResponse,
)
from crm_backend.schemas.tasks import (
    CreateTaskFromTemplateRequest,
    CreateTaskTemplateRequest,
    ExecuteSubtaskActionRequest,
    SetTaskTemplateActivationRequest,
    TaskAttachmentResponse,
    TaskDetailResponse,
    TaskSummaryResponse,
    TaskTemplateResponse,
    UpdateTaskTemplateRequest,
    UnassignedSubtaskQueueResponse,
    UpdateSubtaskProgressRequest,
)

__all__ = [
    "AccessPendingResponse",
    "ActiveMembershipResponse",
    "AuthenticatedUserResponse",
    "ContextSelectionRequiredResponse",
    "ErrorDetailResponse",
    "ErrorResponse",
    "ClientLocationPayload",
    "ClientLocationResponse",
    "ClientSummaryResponse",
    "CreateClientRequest",
    "UpdateClientRequest",
    "CrmUserOptionResponse",
    "CreateLocationRequest",
    "ConfirmDispatchItemRequest",
    "CreateInventoryRequestRequest",
    "CreateTaskDispatchRequest",
    "InventoryDispatchItemResponse",
    "InventoryDispatchResponse",
    "InventoryRequestItemResponse",
    "InventoryRequestResponse",
    "InventorySourceFlowResponse",
    "LoginRequest",
    "LoginSuccessResponse",
    "MembershipOptionResponse",
    "LocationResponse",
    "RequiredMaterialResponse",
    "RequiredMaterialWriteRequest",
    "ReviewInventoryRequestRequest",
    "TokenBundleResponse",
    "CreateStockProductRequest",
    "StockAdjustmentRequest",
    "StockCategoryResponse",
    "StockProductResponse",
    "CreateTaskFromTemplateRequest",
    "CreateTaskTemplateRequest",
    "ExecuteSubtaskActionRequest",
    "SetTaskTemplateActivationRequest",
    "TaskAttachmentResponse",
    "TaskDetailResponse",
    "TaskSummaryResponse",
    "TaskTemplateResponse",
    "UpdateTaskTemplateRequest",
    "UnassignedSubtaskQueueResponse",
    "UpdateSubtaskProgressRequest",
]
